Загружаю первую версию ДЗ№2
solncevx1/FocusStartHomeworks pull request #1
Opened 2020-10-27 06:02 UTC by solncevx1

1. Создал потокобезопасный массив, работающий с основными типами данных.
2. Убедился, что в условиях выполнения двух асинхронных задач в параллельной очереди, массив обрабатывает данные корректно.

2020-10-27 06:17 UTC, GkFoxes commented
Не совсем понимаю, почему я на ревью? Это же дз 1 блока, необходимо Игоря поставить и он потом определит

2020-10-27 06:19 UTC, solncevx1 commented
Ой пардон, я случайно)

вт, 27 окт. 2020 г. в 13:18, Dmitriy Matveenko <notifications@github.com>:

> Не совсем понимаю, почему я на ревью? Это же дз 1 блока, необходимо Игоря
> поставить и он потом определит
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/solncevx1/FocusStartHomeworks/pull/1#issuecomment-717012066>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHEU4IJ6WBXQ7O5WUTQMOTLSMZQ2DANCNFSM4TAK5CHQ>
> .
>

2020-10-27 07:36 UTC, korshunigor requested changes
В Workspace-е сломана ссылка на проект с ДЗ №2 (скрин 1). В папке с проектом почему-то два файла с одинаковым названием, нужно подчистить (скрин 2)

<img width="278" alt="Скрин 1" src="https://user-images.githubusercontent.com/17854702/97270371-1b4df700-1840-11eb-853a-f1fd3b55fccb.png">
<img width="696" alt="Скрин 2" src="https://user-images.githubusercontent.com/17854702/97270365-18530680-1840-11eb-85ac-89cfc365ac46.png">

2020-10-28 19:12 UTC, korshunigor requested changes
Нужны доработки

2020-10-28 19:12 UTC, korshunigor commented on Homework__2/Homework__2/SafeArrayModel.swift
> +
Давай все-таки поудаляем лишние переносы строк в методах

2020-10-28 19:12 UTC, korshunigor commented on Homework__2/Homework__2/SafeArrayModel.swift
> +    }
Флаг "барьер" нужен для того чтобы гарантировать, что в момент выполнения задачи с барьером у нас не будет выполнения ни каких других асинхронных задач. Использовать барьеры целесообразно тогда, когда у нас происходит изменение данных для исключения возможного состояния гонки, в случае запроса данных у нас проблем ни каких не может быть, если одновременно 1000 задач попытается обратиться к нашему массиву, в данном случае барьеры только замедлят выполнение программы.

2020-10-28 19:12 UTC, korshunigor commented on Homework__2/Homework__2/SafeArrayModel.swift
> +final class ThreadSafeArray<T> {
Отсутствует реализация метода contains.

2020-10-28 19:12 UTC, korshunigor commented on Homework__2/Homework__2/ViewController.swift
> +
давай все-таки подавляем лишние пустые строки

2020-10-28 19:12 UTC, korshunigor commented on Homework__2/Homework__2/ViewController.swift
> +            safeArray.append(i)
Давай привыкать придерживаться одинакового стиля написания кода, по этому везде где происходит обращение к переменным на уровне self явно укажем это

2020-10-28 19:12 UTC, korshunigor commented on Homework__2/Homework__2/ViewController.swift
> +    }
А зачем нам 2 одинаковых функции, если можно создать одну функцию task и просто вызвать ее дважды?)

2020-10-28 19:12 UTC, korshunigor commented on Homework__2/Homework__2/ViewController.swift
> +        }
По условию `print(self.safeArray.count)` должен делаться только после завершения выполнения обеих асинхронных задач.

2020-11-05 08:38 UTC, merged

2020-11-06 16:31 UTC, korshunigor reviewed
Жаль что задание было смежено раньше, чем был поставлен апрув...

2020-11-06 16:31 UTC, korshunigor commented on Homework__2/Homework__2/SafeArrayModel.swift
> +     func removeItem(index: Int) {
Появился лишний пробел перед func, ну или одного пробела не хватает перед фигурной скобкой выше. Одна из причин почему рекомендовали настроить Xcode так, чтобы он добавлял табы =)

2020-11-06 16:31 UTC, korshunigor commented on Homework__2/Homework__2/SafeArrayModel.swift
> +        }
Код уехал в сторону.
Полезные комбинации:
command + A - выделить весь код в файле
control + I - провести форматирование файла

2020-11-06 16:31 UTC, korshunigor commented on Homework__2/Homework__2/SafeArrayModel.swift
> +    func contains(where item: (T) -> Bool) -> Bool {
Не соответствует условию )
Нужно было реализовать метод contains, который принимает на вход элемент, но в данном случае мы получаем замыкание. Оно работает и реализация корректная, но давай все таки добавим еще реализацию которая была указана по условию.

Для реализации метода contains требуется, чтобы тип T реализовывал протокол Equitable, для того чтобы не накладывать это ограничение на всю коллекцию, можно воспользоваться [расширением с оговоркой whare](https://swiftbook.ru/content/languageguide/generics-in-swift/#extensions-with-a-generic-where-clause)

2020-11-06 16:31 UTC, korshunigor commented on Homework__2/Homework__2/ViewController.swift
> +        print(self.safeArray.count)
В данном случае мы не дожидаемся завершения выполнения обеих асинхронных задач, каждый раз мы будем получать разное значение Count. Давай сделаем доработку, которая позволит нам дождаться выполнения этих задач (не меняя async на sync). Можем воспользоваться DispatchGroup.